In [179]:
# Alana Montoya
# August 16, 2021
# MATH 407 - Linear Optimization
# Project 2

In [180]:
# Part 1: Solving the Problem

# import libraries
import math
import numpy
import sympy

In [181]:
# Let x0 be the kg of corn, x1 be the kg of tankage, and x2 be the kg of alfalfa
# for a single pig and x3, x4, x5 be slack variables. Converting first to
# standard form, then to the dual, and then to standard form, we get the
# following matrices for the dual:

A = numpy.array([[90,30,10,1,0,0],[20,80,20,0,1,0],[40,60,50,0,0,1]])
c = numpy.array([[200],[180],[150],[0],[0],[0]])
b = numpy.array([[35],[30],[25]])

In [182]:
# The origin is feasible so start with y0, y1, y2 as nonbasic and the slack
# variables y3,y4,y5 as basic

B = [3,4,5]
N = [0,1,2]

In [183]:
# Update the dictionary:

print(c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ b)
#c_B^T times A_B^(-1) times b

print()

print(c[N,:].transpose() - c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N])
#c_N^T - c_B^T times A_B^(-1) times A_N

print()

print(numpy.linalg.inv(A[:,B]) @ b)

print()

print(numpy.linalg.inv(A[:,B]) @ A[:,N])

[[0.]]

[[200. 180. 150.]]

[[35.]
 [30.]
 [25.]]

[[90. 30. 10.]
 [20. 80. 20.]
 [40. 60. 50.]]


In [184]:
# Pick x0 to enter since 200 is positive. x0 corresponds to the first column of 
# the matrix.

35/90, 30/20, 25/40

(0.3888888888888889, 1.5, 0.625)

In [185]:
# Pick y3 to be the leaving variable since it has the smallest ratio.

B = [0,4,5]
N = [1,2,3]

In [186]:
# Update the dictionary:

print(c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ b)
#c_B^T times A_B^(-1) times b

print()

print(c[N,:].transpose() - c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N])
#c_N^T - c_B^T times A_B^(-1) times A_N

print()

print(numpy.linalg.inv(A[:,B]) @ b)

print()

print(numpy.linalg.inv(A[:,B]) @ A[:,N])

[[77.77777778]]

[[113.33333333 127.77777778  -2.22222222]]

[[ 0.38888889]
 [22.22222222]
 [ 9.44444444]]

[[ 3.33333333e-01  1.11111111e-01  1.11111111e-02]
 [ 7.33333333e+01  1.77777778e+01 -2.22222222e-01]
 [ 4.66666667e+01  4.55555556e+01 -4.44444444e-01]]


In [187]:
# Pick y2 to enter since 127.77777778 is positive. y2 corresponds to the second
# column of the matrix.

0.38888889/1.11111111e-01, 22.22222222/1.77777778e+01, 9.44444444/4.55555556e+01

(3.5000000135, 1.2499999983125, 0.20731707287091017)

In [188]:
# Pick y5 to be the leaving variable since it has the smallest ratio.

B = [0,2,4]
N = [1,3,5]

In [189]:
# Dual Optimal Dictionary:

print(c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ b)
#c_B^T times A_B^(-1) times b

print()

print(c[N,:].transpose() - c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N])
#c_N^T - c_B^T times A_B^(-1) times A_N

print()

print(numpy.linalg.inv(A[:,B]) @ b)

print()

print(numpy.linalg.inv(A[:,B]) @ A[:,N])

[[104.26829268]]

[[-17.56097561  -0.97560976  -2.80487805]]

[[ 0.36585366]
 [ 0.20731707]
 [18.53658537]]

[[ 2.19512195e-01  1.21951220e-02 -2.43902439e-03]
 [ 1.02439024e+00 -9.75609756e-03  2.19512195e-02]
 [ 5.51219512e+01 -4.87804878e-02 -3.90243902e-01]]


In [190]:
# The dual optimal solution is
# y0 = 0.36585366, y1 = 0, y2 = 0.20731707, y3 = 0, y4 = 18.53658537, y5 = 0 
# and -P = 104.26829268.

# So, translating back to the primal problem, the primal optimal solution is
# x0 = 0.97560976, x1 = 0, x2 = 2.80487805, x3 = 0, x4 = 17.56097561, x5 = 0
# which produces a minimum cost of about 104 cents, which is simply $1.04.

In [191]:
# Part 2: Sensitivity Analysis

# Question 1 (Range Analysis of the Objective Function):
#       Is the current solution still optimal if the price of corn increases?
#       If so, how much can it increase?

# Convert the original problem into standard form to obtain the desired matrices.

A = numpy.array([[-90,-20,-40,1,0,0],[-30,-80,-60,0,1,0],[-10,-20,-50,0,0,1]])
c = numpy.array([[-35],[-30],[-25],[0],[0],[0]])
b = numpy.array([[-200],[-180],[-150]])

#       Note: doing this means that instead of finding what would happen if we
#             replaced 35 in the vector c with some other value, we want to
#             rather find what would happen if we replaced -35. 35 applies to
#             the original problem (not in standard form) and -35 applies to the
#             standard form of the original problem. Then, at the end we can
#             multiply the inequality solution by -1 to get the inequality
#             solution for the original problem that is not in standard form.

In [192]:
# Define Deltac

Deltac = numpy.array([[1],[0],[0],[0],[0],[0]])

In [193]:
# Define the basic and nonbasic varibles that produced the optimal solution for
# the primal problem.

B = [0,2,4]
N = [1,3,5]

In [194]:
# Compute (c_n^T - c_B^T * A_B^{-1} * A_N) + t(Deltac_N^T - Deltac_B^T * A_B^{-1} * A_N)
print(c[N,:].transpose() - c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N])
# (c_n^T - c_B^T * A_B^{-1} * A_N)

print()

print(Deltac[N,:].transpose() - Deltac[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N])
# Deltac_N^T - Deltac_B^T * A_B^{-1} * A_N

[[-18.53658537  -0.36585366  -0.20731707]]

[[-0.04878049  0.01219512 -0.0097561 ]]


In [195]:
# Store these calculations to make accessing the numbers easy.

c1 = c[N,:].transpose() - c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N]
c2 = Deltac[N,:].transpose() - Deltac[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N]

In [196]:
# We want c1 + t*c2 <= 0.

# Define the symbolic variables.
t = sympy.symbols('t')

In [197]:
# Get entries of c1 and c2 using [i,j] (note that both are row vectors).
# Solve a collection of equations/inequalities.
#       The first input set of parenthesis are the inequalities.
#       The second input is the variable.

sympy.solve((c1[0,0]+t*c2[0,0]<=0,c1[0,1]+t*c2[0,1]<=0,c1[0,2]+t*c2[0,2]<=0),t)

(-21.25 <= t) & (t <= 30.0)

In [198]:
# Since these calculations were done to find how much -35 (for standard form of
# original problem) could be increased or decreased, the inequality above needs
# to by multiplied by -1 to determine how much 35 (for original problem not in
# standard form) could be increased of decreased. So, the inequality becomes:
#       -30 <= t <= 21.25
# This means the cost of kg of corn can increase by about 21 cents.

In [199]:
# Question 2 (Pricing in a New Product):
#       The farmer learns that his pigs like apples. As a treat, he decides to
#       start buying them. Apples have
#               70 carbohydates,
#               30 protein, and
#               10 vitamins.
#       However, he will only buy them if his total costs decrease. Assuming the
#       other prices remain the same, how much would the apples need to cost so
#       that buying them reduces his costs?

# Note: the following computations will use the standard form of the original
#       problem. Since we will need to multiply everything by -1 to get to
#       standard form, we will need to multiply our inequality solution by -1 to
#       get the solution to the original problem that is not in standard form.

In [200]:
# Let x6 be the kg of apples and have their original cost be 0 so that B={0,2,4}
# is still the optimal solution.

# Update the previous matrices to include the apples.

A = numpy.array([[-90,-20,-40,1,0,0,-70],[-30,-80,-60,0,1,0,-30],[-10,-20,-50,0,0,1,-10]])
c = numpy.array([[-35],[-30],[-25],[0],[0],[0],[0]])
b = numpy.array([[-200],[-180],[-150]])

In [201]:
# Track changes in the cost of the apples with:
Deltac = numpy.array([[0],[0],[0],[0],[0],[0],[1]])

In [202]:
# Define the basic variables that produced the optimal solution for the primal
# problem and extend the nonbasic varibles to include x6.

B = [0,2,4]
N = [1,3,5,6]

In [203]:
# We want the smallest t so that
# (c_n^T - c_B^T * A_B^{-1} * A_N) + t(Deltac_N^T - Deltac_B^T * A_B^{-1} * A_N)
# has a positive entry in the entry for x6.

# Using B={0,2,4}, compute
# (c_n^T - c_B^T * A_B^{-1} * A_N) + t(Deltac_N^T - Deltac_B^T * A_B^{-1} * A_N)

print(c[N,:].transpose() - c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N])
# (c_n^T - c_B^T * A_B^{-1} * A_N)

print()

print(Deltac[N,:].transpose() - Deltac[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N])
# Deltac_N^T - Deltac_B^T * A_B^{-1} * A_N

[[-18.53658537  -0.36585366  -0.20731707  27.68292683]]

[[0. 0. 0. 1.]]


In [204]:
# Store these calculations to make accessing the numbers easy.

c1 = c[N,:].transpose() - c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N]
c2 = Deltac[N,:].transpose() - Deltac[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N]

In [205]:
# We want c1 + t*c2 > 0.

# Define the symbolic variables.
t = sympy.symbols('t')

In [206]:
# Get entries of c1 and c2 using [i,j] (note that both are row vectors).
# Solve a collection of equations/inequalities.
#       The first input set of parenthesis are the inequalities.
#       The second input is the variable.

sympy.solve((c1[0,3]+t*c2[0,3]>0),t)

(-27.6829268292683 < t) & (t < oo)

In [207]:
# So, −27.6829268292683 < t. But, since we converted the problem to standard
# form (we multiplied the objective function by -1 to create a maximization
# problem), this inequality needs to be multiplied by -1 to translate the cost
# back to the original problem that is not in standard form. So, the inequality
# becomes:
#       t < 27.6829268292683.
# This means the cost of the apples must be less than about 27.68 cents.

In [208]:
# Question 3 (Range Analysis of the Constraints):
#       A new study was released that suggests that pigs who have more than the
#       intially indicated daily intake of vitamins tend to be happier. While it
#       is not necessary for their physical health, the farmer still cares about
#       their mental wellbeing and wants to increase the pig's mimimum daily
#       intake of vitamins. How many vitamins could be added before the optimal
#       solution of buying only corn and alfalfa is affected?

In [209]:
# Using the dual in standard form we get

A = numpy.array([[90,30,10,1,0,0],[20,80,20,0,1,0],[40,60,50,0,0,1]])
c = numpy.array([[200],[180],[150],[0],[0],[0]])
b = numpy.array([[35],[30],[25]])

In [210]:
# The dual's optimal solution had basic and nonbasic variables defined by

B = [0,2,4]
N = [1,3,5]

In [211]:
# Represent changing the 150 entry (indicates the minimum daily vitamin intake)
# as replacing c with c + t*Deltac where

Deltac = numpy.array([[0],[0],[1],[0],[0],[0]])

In [212]:
# Calculating (c_n^T - c_B^T * A_B^{-1} * A_N) + t(Deltac_N^T - Deltac_B^T * A_B^{-1} * A_N)
# with B = {0,2,4} and N = {1,3,5} we get

print(c[N,:].transpose() - c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N])
# (c_n^T - c_B^T * A_B^{-1} * A_N)

print()

print(Deltac[N,:].transpose() - Deltac[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N])
# Deltac_N^T - Deltac_B^T * A_B^{-1} * A_N

[[-17.56097561  -0.97560976  -2.80487805]]

[[-1.02439024  0.0097561  -0.02195122]]


In [213]:
# Store these calculations to make accessing the numbers easy.

c1 = c[N,:].transpose() - c[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N]
c2 = Deltac[N,:].transpose() - Deltac[B,:].transpose() @ numpy.linalg.inv(A[:,B]) @ A[:,N]

In [214]:
# We want c1 + t*c2 <= 0.

# Define the symbolic variables.
t = sympy.symbols('t')

In [215]:
# Get entries of c1 and c2 using [i,j] (note that both are row vectors).
# Solve a collection of equations/inequalities.
#       The first input set of parenthesis are the inequalities.
#       The second input is the variable.

sympy.solve((c1[0,0]+t*c2[0,0]<=0,c1[0,1]+t*c2[0,1]<=0,c1[0,2]+t*c2[0,2]<=0),t)

(-17.1428571428571 <= t) & (t <= 100.0)

In [216]:
# This shows that −17.1428571428571 ≤ t ≤ 100.0 would preserve the solution of 
# buying only corn and alfalfa. So, 100 vitamins could be added before the
# optimal solution is affected.